### ISSUE TITLE
Implementing arbitrary computation on the intersection

### ISSUE THREAD

**Issue by zaczanussi** [microsoft/APSI#14]
In an earlier paper ([CHLR18](https://eprint.iacr.org/2018/787), section 6) the authors briefly outline an extension of the protocol to allow computation on the intersection. This is achieved by returning secret shares of the labels which are then forwarded to a secondary two-party MPC protocol.

Some colleagues and I are investigating the possibility of extending this library to perform this functionality. The computations in question are summary statistics. For example, the Sender is a credit card company with labels that are the values of transactions, and the Receiver has both qualitative and numerical labels on each of the respondents. We would like to compute aggregates of the transactions based on the qualities of respondents.

I was wondering if you had any thoughts on how one could go about adapting this code to add this functionality? How much work do you think it would take? If we went ahead with implementing this, I'm sure we could submit a pull request, if desired. We are considering using [ABY](https://github.com/encryptogroup/ABY) to facilitate the MPC portion. 

Thanks!

**Comment by kimlaine** [comment]
Some computation on the intersection is very easy to do, namely, cardinality. All the sender needs to do in the OPRF phase is permute the response before sending it back. Now the receiver can't tell which items actually intersected but can still reliably compute the cardinality. The problem with all these cardinality protocols is that the security model is kind of weak in practice, as the receiver can modify slightly and repeat the query to find information about which items really intersected.

More general computation in the labeled case really interesting, but maybe challenging because we now always use OPRF and the labels are encrypted by XORing with a mask derived from the OPRF value for each item, which is different from the 2018 paper. I'm not entirely sure what is the best way to do this.

**Comment by zaczanussi** [comment]
Hmm, I suppose I've done most of my reading on the 2018 paper. I should dive a little deeper into the 2021 paper.

Hypothetically, letting the labels be secret shares of the Sender's data should still work, if I'm understanding correctly. This can be done by preprocessing the Sender's labels and passing secret shared values into the APSI protocol. The rest of the work comes from the sending the Receiver's shares to the Sender. 

I'm going to keep thinking on this. If you have any further advice, please don't hesitate to share! Closing for now.
