### ISSUE TITLE
installing error

### ISSUE THREAD

**Issue by Hang-shao** [microsoft/APSI#17]
build error:
![image](https://user-images.githubusercontent.com/50350694/157227031-c838ccaf-4fd0-461a-9f2a-eb0242abbe4f.png)

**Comment by kimlaine** [comment]
APSI requires SEAL to be built with the CMake option `-DSEAL_THROW_ON_TRANSPARENT_CIPHERTEXT=OFF`. Are you installing SEAL with vcpkg? If so, use `./vcpkg install seal[no-throw-tran]` to install the SEAL package (this is explained [here](https://github.com/Microsoft/APSI#building-and-installing-apsi-manually)). Or perhaps you have another installation of SEAL available in your system and CMake is picking up that one instead of the one use perhaps installed with vcpkg?

**Comment by Hang-shao** [comment]
> APSI requires SEAL to be built with the CMake option `-DSEAL_THROW_ON_TRANSPARENT_CIPHERTEXT=OFF`. Are you installing SEAL with vcpkg? If so, use `./vcpkg install seal[no-throw-tran]` to install the SEAL package (this is explained [here](https://github.com/Microsoft/APSI#building-and-installing-apsi-manually)). Or perhaps you have another installation of SEAL available in your system and CMake is picking up that one instead of the one use perhaps installed with vcpkg?

 Thank you for your reply. I installed with vcpkg. The question is exactly what you said. I have installed seal separately before. Should I delete the previously installed seal and reinstall with vcpkg?

**Comment by kimlaine** [comment]
Maybe the simplest thing would be to remove your non-vcpkg install of SEAL and reinstall with vcpkg.

**Comment by Hang-shao** [comment]
ok, thanks.
