### ISSUE TITLE
How to understand the Frobenius operation？

### ISSUE THREAD

**Issue by TY-cc** [microsoft/APSI#37]
As the  theme， I want  to know more details about Frobenius operation.  its theory-base and concrete-flow

**Comment by kimlaine** [comment]
We don't use the Frobenius in APSI. I'm assuming you are referring to the ideas we presented in [eprint:2021/1116](https://eprint.iacr.org/2021/1116). These were implemented in a totally custom (not open-sourced) implementation with [HElib](https://github.com/homenc/HElib), since [SEAL](https://GitHub.com/Microsoft/SEAL) doesn't support such encrypted operations.

**Comment by TY-cc** [comment]
Oh, thanks.  I am  learning the paper about https://eprint.iacr.org/2021/1116.  But i want to know about Frobenius operation. what i should read and learn?

**Comment by kimlaine** [comment]
I see. Well, I guess first of all you may want to read some basic algebraic number theory textbook. Then you could look at [eprint:2011/566](https://eprint.iacr.org/2011/566.pdf).

**Comment by TY-cc** [comment]
Thank you very much. I will read this paper.
