### ISSUE TITLE
Can I compile and run APSI in Android?

### ISSUE THREAD

**Issue by clearlovel7** [microsoft/APSI#42]
As the title, I want to run APSI on an Android phone. Now I want to know whether APSI supports compiling and running in the Android environment.

**Comment by kiromaru** [comment]
Hello,

Not out of the box, but this can definitely be done. Since APSI is a CMake project, you should be able to configure it to build for an Android environment.

You would need to:

- Create a new "Native C++" project in Android Studio: This creates a small app that communicates with native C++ code in a library that is configured using CMake
- Replace the C++ code in the project with the APSI source code
- Modify app/build.gradle to provide CMake with the appropriate configuration parameters. I recommend you take a look at [how this is done in the SEAL library](https://github.com/microsoft/SEAL/blob/eb834e2cc159fa1e61520450c577fb2aac64d54b/android/app/build.gradle).

In your CMake configuration you should use vcpkg to provide the dependencies that are needed by APSI, as specified in the README.md file.
