### ISSUE TITLE
Parameters setting for labeld mode

### ISSUE THREAD

**Issue by xianglingzhang** [microsoft/APSI#45]
Hi!
I built APSI on Ubuntu 20.04 with a single Intel i7-8700 3.20GHz CPU (8 physical cores) and 16 GB RAM, but the labeled mode is very slow compared to the unlabeled mode. Here is the information when I choose parameters in 16M-11041.json with |X| = 2^20 and |Y| = 1024. I have tried 16M-5535.json and 256M-4096.json, same situation. How to choose the parameters in labeled mode?

```
$../../bin/sender_cli -d db.csv --port 60000 -p ../../parameters/16M-11041.json -t 1
time info
INFO  20:25:29:041.062: OPRFSender::ComputeHashes (labeled) :     1 instances. Duration:  20047ms
INFO  20:25:29:041.084: OPRFSender::ProcessQueries          :     1 instances. Duration:     15ms
INFO  20:25:29:041.112: Sender::ComputePowers               :    10 instances. Average:     754ms Minimum:    751ms Maximum:    763ms
INFO  20:25:29:041.142: Sender::ProcessBinBundleCache       :    20 instances. Average:     264ms Minimum:     21ms Maximum:    496ms
INFO  20:25:29:041.173: Sender::RunOPRF                     :     1 instances. Duration:     15ms
INFO  20:25:29:041.204: Sender::RunParams                   :     1 instances. Duration:      0ms
INFO  20:25:29:041.234: Sender::RunQuery                    :     1 instances. Duration:  12861ms
INFO  20:25:29:041.264: SenderDB::Load                      :     1 instances. Duration:     83ms
INFO  20:25:29:041.294: SenderDB::generate_caches           :     1 instances. Duration: 529694ms
INFO  20:25:29:041.325: SenderDB::insert_or_assign (labeled):     1 instances. Duration: 556915ms
INFO  20:25:29:041.352: ZMQSenderDispatcher::dispatch_oprf  :     1 instances. Duration:     15ms
INFO  20:25:29:041.372: ZMQSenderDispatcher::dispatch_params:     1 instances. Duration:      0ms
INFO  20:25:29:041.385: ZMQSenderDispatcher::dispatch_query :     1 instances. Duration:  12867ms
INFO  20:25:29:041.397: insert_or_assign_worker             :    10 instances. Average:     509ms Minimum:    482ms Maximum:    549ms
INFO  20:25:29:041.414: preprocess_labeled_data             :     1 instances. Duration:   1405ms

comm info
INFO  20:25:12:915.809: Communication R->S: 11647 KB
INFO  20:25:12:915.813: Communication S->R: 7015 KB
INFO  20:25:12:915.816: Communication total: 18663 KB
```

**Comment by kimlaine** [comment]
Some of the parameter sets are tuned for the labeled mode. For example, [1M-4096-32.json](https://github.com/microsoft/APSI/blob/main/parameters/1M-4096-32.json) is meant for 32-byte labels. In labeled mode, the S->R communication is linear in the size of the labels, so it's increased from the labeled mode. Hence, the idea with these parameters is to generally push for smaller S->R communication and overemphasize the R->S communication.

The labeled mode is often thought of as slow because the pre-processing (adding items to the SenderDB) is much much slower than in unlabeled mode. This is because the labeled mode needs to do polynomial interpolation, which the unlabeled mode does not need to do. Therefore, in labeled mode, it's particularly important that you persist the SenderDB and add to it/remove from it, rather than create it separately for each execution of the protocol.

**Comment by xianglingzhang** [comment]
Thank you for your reply! I have another question. Does the labeled polynomial have to be G(y) = rF(y)+H(y), in which F(y) = 0 and H(y) = v for y in Y, and v is the related label?  what if just use the H(y)?
