### ISSUE TITLE
Failed to load SenderDB: ios_base::failbit set: iostream stream error

### ISSUE THREAD

**Issue by xdutjz** [microsoft/APSI#63]
Excuse me, I have an unsolved issue when running the release CLI, when sender.cli loading DB, it reports Failed to load SenderDB: ios_base::failbit set: iostream stream error. 

As a result, no match result can be found in PSI. The CLI indicates that sender can load the DB file and count items, but the items can't be read properly.

I've looked into the sender.cpp, `auto [data, size] = SenderDB::Load(fs);` cant' be operated, however it seems that no error code in `pair<SenderDB, size_t> SenderDB::Load(istream &in)` matches.         

I've also checked following functions respectively, `pair<SenderDB, size_t> SenderDB::Load(istream &in)`, `vector<unsigned char> read_from_stream(istream &in)`, `void read_from_stream(istream &in, uint32_t byte_count, vector<unsigned char> &destination)`, and finally `in.read(reinterpret_cast<char *>(destination.data() + old_size), to_read);`. It seems that the input  stopped before reaching the last function `in.read` in `utils.cpp`.

1. I checked both SenderDB and query CSV, then I cleared both database and filled in simple data, the problem still exists.
2. I use VCPKG to install dependencies but CMAKE to link.
3. VS failed to automatically link jsoncpp and zlib when build and release.
4. In solution, the reference part reports that The "Microsoft.VisualStudio.ProjectSystem.References.UnresolvedBuildDependencyProjectReference" reference could not be resolved.
5. I use following command in powershell,
   a. python .\test_data_creator.py 10000 100 10
   b. .\sender_cli.exe -d .\SenderDB.csv -p .\1M-256.json -t 1 -l all
   c. .\receiver_cli.exe -q .\query.csv -t 1 -o .\testresult.csv -l all

BTW, There are undeclared identifier issues arising from character encoding in Chinese version VS, in db_encoding.cpp.

Sorry that I'm quite new to CPP, so I was wondering if there is any chance that mentioned problems cause iostream stream error. Or maybe it is because only a specific encoding is accepted as input.

Cheers.

**Comment by xdutjz** [comment]
![UnresolvedBuildDependencyProjectReference](https://github.com/microsoft/APSI/assets/42059676/e6a37091-dff4-4d29-8cf4-27d75a83f8fb)

**Comment by xdutjz** [comment]
It is partly resolved.

The PSI can be correctly performed with utf-8 and  a slightly change in `test_data_creator.py`.

`item = ''.join(random.choice(letters) for i in range(item_bc)) + ','`, so there will be an ',' at the end of each item in test csv.

However, the CLI still reports `Failed to load SenderDB: ios_base::failbit set: iostream stream error`.

**Comment by kimlaine** [comment]
This is not the right fix. It's not clear what the problem exactly is, but there does seem to be some major confusion going on.

1. Did `receiver_cli.exe` actually output the correct result?g
1. Your list of commands seems to be missing something. The data creation script outputs a `db.csv`, but you call `sender_cli.exe` with a `SenderDB.csv`. Where did this come from?
1. Since you are printing all output (`-l all`) you are getting the failure message of loading the `SenderDB` as a binary serialized object (see below). This is normal and you should see this if you give it a CSV file as input.
1. Just to clarify, the idea of `SenderDB::Load` is that if your sender's dataset is large, it's possible to serialize and deserialize the `SenderDB` object. This is to avoid the costly precomputations that are done when you insert items in a `SenderDB`. However, you are not (according to the commands you showed) serializing the `SenderDB` at any point. This can be done with `sender_cli.exe` using the `--sdbOutFile <filename>` option. To quickly load the `SenderDB` now to another run of the `sender_cli.exe`, you'd just use the `--dbFile <filename>` option. Note that in this case it wouldn't be a CSV file but a binary file. The loading procedure in `sender_cli.exe` is such that it will first try loading the input file you give with `--dbFile` (`-d`) as a binary serialized `SenderDB` object and, if that fails, try to load it as a CSV file.

With some filename changes the commands you provided seem to work for me. The output about a failed read is normal. If you are getting the wrong result from `receiver_cli.exe`, my guess with this information would be that you might be simply giving it an old `SenderDB.csv` that has no items in common with your `query.csv` since there are some filename changes going on here.

**Comment by JiezhenJasonTang** [comment]
Thanks for the reply and inform me about `SenderDB`.

I changed the filename of script output so it may looks like a little bit confusing, but in each command I used the correct file. 

And the `receiver_cli.exe` can output the correct result indeed.

Cheers.
