### ISSUE TITLE
Some questions about query_params and seal_params

### ISSUE THREAD

**Issue by ElleryQu** [microsoft/APSI#64]
Hi. Taking 1M-1024-cmp.json for example, for `query_powers = [ 1, 3, 4, 5, 8, 14, 20, 26, 32, 38, 44, 47, 48, 49, 51, 52 ]`, I get inner depth = 0, outer depth = 1. and the entire circuit depth should be 2. However, `coeff_modulus_bits = [ 40, 32, 32 ]` should only support a circuit of depth 1, in my viewpoint. Is there anything I missing here?

**Comment by kimlaine** [comment]
The `query_powers` you gave can compute monomials up to degree 104 with depth 1, but you still need to multiply the result with the plaintext coefficients that come from the `SenderDB` preprocessing. So in that sense the full matching polynomial is depth 2. However, you are not saying what your `plain_modulus` is. After the monomials are computed, each is modulus switched down so that the ciphertext coefficients are in the lowest possible SEAL parameter set, with just a single 40-bit prime as `coeff_modulus`. As long as `plain_modulus` is small enough, you can still do that plaintext-ciphertext multiplication without overflowing the noise bound. This is why it works. There is no need for modulus switching after the plaintext multiplication.
