### ISSUE TITLE
Receiver may get a mismatch result?

### ISSUE THREAD

**Issue by Yanghello** [microsoft/APSI#8]
Hi, I have a problem when reading `Practice` in `README.md`.
If the receiver has an `itemX` that is not match sender's items, but its first part `itemX-part1` match `item416-part1`, and the second part `itemX-part2` match `item12-part2`. Does the receiver get the PSI 'match' result of `itemX`?

**Comment by kimlaine** [comment]
Yes, it would show up as a false positive match, but is very unlikely to happen because the item length is so long. The total item length is lower-bounded to 80 bits in the implementation and in many parameterizations is well over 100 bits. Of course the item is split into multiple parts (2 parts in the toy example in README.md) and for each part the probability of a false match is independently increased due to the size of the bin bundle (2 in the toy example). In practice, this size is not so big that it would significantly change the fact that getting a false positive is extremely unlikely.

**Comment by Yanghello** [comment]
I see. Thanks!
